import React from "react";
import { NextSeo } from 'next-seo';

const Disclaimer = () => {
  return (
    <>
      <NextSeo 
        title="Disclaimer - AI Image Generator"
        description="Important disclaimer and legal information about using AI Image Generator services and AI-generated content."
        canonical="https://aiimagegenerator.site/disclaimer/"
        noindex={true}
        nofollow={true}
        openGraph={{
          url: "https://aiimagegenerator.site/disclaimer/",
          title: "Disclaimer - AI Image Generator",
          description: "Important disclaimer and legal information about using AI Image Generator services and AI-generated content.",
          images: [
            {
              url: "https://aiimagegenerator.site/og-image.png",
              width: 1200,
              height: 630,
              alt: "Disclaimer"
            }
          ],
          type: "website",
        }}
        twitter={{
          cardType: "summary_large_image",
        }}
      />
      <div className="max-w-4xl mx-auto py-8 px-4">
        <h1 className="text-3xl font-bold mb-8">Disclaimer</h1>
        <div className="prose prose-lg max-w-none">
          {/* Removed last updated */}
          <h2 className="mt-8 mb-2">General Information</h2>
          <p>AI Image Generator provides AI-powered image creation tools for informational and entertainment purposes only. We do not guarantee the accuracy, completeness, or suitability of any generated content.</p>
          <h2 className="mt-8 mb-2">AI-Generated Content</h2>
          <p>All images and text generated by our platform are created by artificial intelligence. Results may not always be accurate, appropriate, or error-free. Use generated content at your own discretion.</p>
          <h2 className="mt-8 mb-2">No Professional Advice</h2>
          <p>Nothing on this site constitutes professional, legal, or financial advice. Always consult a qualified professional for specific guidance.</p>
          <h2 className="mt-8 mb-2">External Links</h2>
          <p>Our website may contain links to third-party sites. We are not responsible for the content or privacy practices of external sites.</p>
          <h2 className="mt-8 mb-2">Limitation of Liability</h2>
          <p>AI Image Generator is not liable for any losses or damages resulting from the use of our services or reliance on generated content.</p>
          <h2 className="mt-8 mb-2">Contact</h2>
          <p>If you have questions about this disclaimer, please use our <a href="/contact" className="text-blue-600 hover:underline">Contact page</a>.</p>
        </div>
      </div>
    </>
  );
};

export default Disclaimer; 